### ISSUE TITLE
Add rclone and s5cmd to coder docker image

### ISSUE THREAD

**Issue by dcarrion87** [harrison-ai/cobalt-docker-coder-dev#7]
[s5cmd](https://github.com/peak/s5cmd) is useful for fast s3 file transfer and fast disk usage reports.

[rclone](https://rclone.org/) is good for copying files between different s3 providers.

Add these to the [docker image](https://github.com/harrison-ai/cobalt-docker-coder-dev/blob/main/base/Dockerfile) so users don't have to download these themselves.

**Comment by andychisholm** [comment]
https://harrison-ai.atlassian.net/wiki/spaces/HAI/pages/1895694341/Getting+started#Copy-files-between-Flashblade-and-AWS-S3

**Comment by dcarrion87** [comment]
Nice one for picking this up @guillaume-troadec!

One approach would be to pull specific release binaries into the image and extract it to /usr/local/bin. E.g.: 

```
curl ... https://github.com/peak/s5cmd/releases/download/v${S5CMD_VERSION}/s5cmd_${S5CMD_VERSION}_Linux-64bit.tar.gz
tar xfz ...
```

Similar to what was done here:

```
ARG AWS_VERSION=2.7.18
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-${AWS_VERSION}.zip" -o "/tmp/awscliv2.zip" && \
    unzip -q /tmp/awscliv2.zip -d /tmp && \
    /tmp/aws/install && \
    rm -rf /tmp/aws /tmp/awscliv2.zip
```

You could probably get clever depending on the architecture version too if you're feeling keen. But at the moment we're only supporting 64-bit (x86_64) so not required.

**Comment by dcarrion87** [comment]
This issue has been migrated to Jira: https://harrison-ai.atlassian.net/browse/HPF-171
